#!/usr/bin/env python

import os
import subprocess
import time
import select
import Xlib
import Xlib.display
import fcntl
import errno
import socket

DVORAK, QWERTY = 0, 1
LINUX, WINDOWS = 0, 1

POSITION = LINUX
LINUX_LAYOUT, WINDOWS_LAYOUT = DVORAK, DVORAK

DEVNULL = os.open(os.devnull, os.O_RDWR)

def read_lines(fd):
  buf = ""
  while True:
    try:
      f = os.read(fd, 8192)
    except OSError, e:
      if e.errno == errno.EAGAIN:
        yield None
        continue
      raise

    if not f:
      break
    tokens = (buf + f).split("\n")
    buf = tokens.pop(-1)
    for line in tokens:
      yield line

def determine_layout():
  p = subprocess.Popen(["setxkbmap", "-query"], stdin=DEVNULL, stdout=subprocess.PIPE, stderr=None, shell=False, bufsize=16300)
  p.wait()

  if p.returncode != 0:
    raise Exception("Bad return code: %d" % p.returncode)

  data = os.read(p.stdout.fileno(), 65535)
  p.stdout.close()

  for l in data.split("\n"):
    if not l.startswith("layout: "):
      continue

    value = l.split(None, 2)[1]
    if value == "dvorak":
      return DVORAK
    if value == "gb":
      return QWERTY
    break

  raise Exception("unable to detect layout")

def beep():
  subprocess.check_call(["beep", "-f", "830", "-l", "100"])

SOCKET = None
def switch_layout():
  print "must switch layout..."

  global SOCKET
  if SOCKET is None:
    SOCKET = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    SOCKET.connect(("192.168.180.1", 5566))

  time.sleep(0.2)
  SOCKET.send("keyboard")
  beep()

def dump():
  print "{position=%s, linux=%s, windows=%s}" % ("linux" if POSITION == LINUX else "windows", "dvorak" if LINUX_LAYOUT == DVORAK else "qwerty", "dvorak" if WINDOWS_LAYOUT == DVORAK else "qwerty")

def enter_linux():
  print "entering linux..."

  global POSITION
  POSITION = LINUX
  if WINDOWS_LAYOUT != LINUX_LAYOUT:
    switch_layout()

  dump()

def enter_windows():
  print "entering windows..."

  global POSITION
  POSITION = WINDOWS
  if WINDOWS_LAYOUT != LINUX_LAYOUT:
    switch_layout()

  dump()

def terminating():
  # do nothing
  pass

def layout_changed():
  print "layout changed"

  global WINDOWS_LAYOUT, LINUX_LAYOUT
  new_layout = determine_layout()
  if POSITION == LINUX:
    LINUX_LAYOUT = new_layout
  else:
    WINDOWS_LAYOUT = new_layout

  dump()

def handle_stdin(reader):
  # [2017-10-01T16:25:05] INFO: entering screen
  # 0123456789012345678901
  for line in reader:
    if line is None:
      return

    print line
    if not line or line[0] != "[":
      continue

    l = line[20:]
    if l == "] INFO: leaving screen":
      enter_windows()
    elif l == "] INFO: entering screen":
      enter_linux()

def handle_display_event(event):
  if event.type != 34 or event.request != 0:
    return

  print "display event triggered"
  layout_changed()

def handle_display(display):
  i = display.pending_events()
  while i > 0:
    event = display.next_event()
    handle_display_event(event)
    i-=1

def set_nonblocking(fd):
  flags = fcntl.fcntl(0, fcntl.F_GETFL, 0) | os.O_NONBLOCK
  fcntl.fcntl(0, fcntl.F_SETFL, flags)

def main():
  dump()

  set_nonblocking(0)

  display = Xlib.display.Display()
  root = display.screen().root
#  root.change_attributes(event_mask=Xlib.X.MappingNotifyMask)

  display_fd = display.fileno()

  reader = read_lines(0)
  fds, empty = [display_fd, 0], []
  while True:
    r, _, _ = select.select(fds, empty, empty)

    for fd in r:
      if fd == 0:
        handle_stdin(reader)
      elif fd == display_fd:
        handle_display(display)
      else:
        raise Exception("bad fd")

  terminating()

if __name__ == "__main__":
  try:
    main()
  except KeyboardInterrupt:
    pass
