#!/usr/bin/python3

import os
import subprocess
import time
import select
import Xlib
import Xlib.display
import fcntl
import errno
import socket
import process
import sys

DVORAK, QWERTY = 0, 1
LINUX, WINDOWS = 0, 1

POSITION = LINUX
LINUX_LAYOUT, WINDOWS_LAYOUT = DVORAK, DVORAK

DEVNULL = os.open(os.devnull, os.O_RDWR)

def read_lines(fd):
  buf = b""
  while True:
    try:
      f = os.read(fd, 8192)
    except OSError as e:
      if e.errno == errno.EAGAIN:
        yield None
        continue
      raise

    if not f:
      break
    tokens = (buf + f).split(b"\n")
    buf = tokens.pop(-1)
    for line in tokens:
      yield line

def determine_layout():
  p = subprocess.Popen(["setxkbmap", "-query"], stdin=DEVNULL, stdout=subprocess.PIPE, stderr=None, shell=False, bufsize=16300)
  p.wait()

  if p.returncode != 0:
    raise Exception("Bad return code: %d" % p.returncode)

  data = os.read(p.stdout.fileno(), 65535)
  p.stdout.close()

  for l in data.split(b"\n"):
    if not l.startswith(b"layout: "):
      continue

    value = l.split(None, 2)[1]
    if value == b"dvorak":
      return DVORAK
    if value == b"gb":
      return QWERTY
    break

  raise Exception("unable to detect layout")

def beep():
  subprocess.check_call(["beep", "-f", "830", "-l", "100"])

SOCKET = None
def switch_layout():
  print("must switch layout...")

  global SOCKET
  if SOCKET is None:
    SOCKET = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    SOCKET.connect(("192.168.180.1", 5566))

  time.sleep(0.2)
  SOCKET.send(b"keyboard")
  beep()

def dump():
  print("{position=%s, linux=%s, windows=%s}" % ("linux" if POSITION == LINUX else "windows", "dvorak" if LINUX_LAYOUT == DVORAK else "qwerty", "dvorak" if WINDOWS_LAYOUT == DVORAK else "qwerty"))

LAST_QEMU = None
def get_qemu_tids():
  global LAST_QEMU
  if LAST_QEMU is not None:
    pid, start_time, tids = LAST_QEMU
    if process.start_time(pid) == start_time:
      return tids

  pid = process.find_qemu_vm(QEMU_BINARY, VM_UUID)
  if pid is None:
    return None

  start_time = process.start_time(pid)
  tids = list(process.get_cpu_tids(pid))
  LAST_QEMU = pid, start_time, tids
  print("updated qemu thread ids:", tids)
  return tids

def set_priority(rt):
  tids = get_qemu_tids()
  if not tids:
    return

  print("set priority", "rt" if rt else "ot")

  try:
    process.set_rt(tids, rt)
  except PermissionError:
    print("permission error -- use capwrap")
  except OSError:
    pass

def enter_linux():
  print("entering linux...")

  global POSITION
  POSITION = LINUX
  if WINDOWS_LAYOUT != LINUX_LAYOUT:
    switch_layout()

  set_priority(False)
  dump()

def enter_windows():
  print("entering windows...")

  global POSITION
  POSITION = WINDOWS
  if WINDOWS_LAYOUT != LINUX_LAYOUT:
    switch_layout()

  set_priority(True)
  dump()

def terminating():
  # do nothing
  pass

def layout_changed():
  print("layout changed")

  global WINDOWS_LAYOUT, LINUX_LAYOUT
  new_layout = determine_layout()
  if POSITION == LINUX:
    LINUX_LAYOUT = new_layout
  else:
    WINDOWS_LAYOUT = new_layout

  dump()

def handle_stdin(reader):
  # [2017-10-01T16:25:05] INFO: entering screen
  # 0123456789012345678901
  for line in reader:
    if line is None:
      return

    os.write(1, line + b"\n")
    if not line or line[0] != ord(b"["):
      continue

    l = line[20:]
    if l == b"] INFO: leaving screen":
      enter_windows()
    elif l == b"] INFO: entering screen":
      enter_linux()

def handle_display_event(event):
  if event.type != 34 or event.request != 0:
    return

  print("display event triggered")
  layout_changed()

def handle_display(display):
  i = display.pending_events()
  while i > 0:
    event = display.next_event()
    handle_display_event(event)
    i-=1

def set_nonblocking(fd):
  flags = fcntl.fcntl(0, fcntl.F_GETFL, 0) | os.O_NONBLOCK
  fcntl.fcntl(0, fcntl.F_SETFL, flags)

def main(qemu_binary, vm_uuid):
  # HACK
  global QEMU_BINARY, VM_UUID
  QEMU_BINARY = qemu_binary
  VM_UUID = vm_uuid

  dump()

  set_nonblocking(0)

  display = Xlib.display.Display()
  root = display.screen().root
#  root.change_attributes(event_mask=Xlib.X.MappingNotifyMask)

  display_fd = display.fileno()

  reader = read_lines(0)
  fds, empty = [display_fd, 0], []
  while True:
    r, _, _ = select.select(fds, empty, empty)

    for fd in r:
      if fd == 0:
        handle_stdin(reader)
      elif fd == display_fd:
        handle_display(display)
      else:
        raise Exception("bad fd")

  terminating()

if __name__ == "__main__":
  if len(sys.argv) < 3:
    print("args: %s [qemu binary] [vm uuid]" % sys.argv[0], file=sys.stderr)
    sys.exit(1)
  try:
    main(sys.argv[1], sys.argv[2])
  except KeyboardInterrupt:
    pass
